# Step by Step - Classification

1. Prepare your dataframe (pandas)
2. Organise your columns, get the label/target on the end of the array.
3. Get into a numpy array np.array(df) or df.as_matrix <-matrix method is expiring
4. X = slice (All Rows)
5. y = slice
6. scale X, normailzes the data, it divides the data by the mean to put it to scale for analysis.
7. train_test_split = Xtrain, ytrain, Xtest, ytest
8. SKLearn cheat sheet for best method. http://scikit-learn.org/stable/tutorial/machine_learning_map/index.html
9. Fit the model.
10. Predoct.
11. Analyse Metrics.


In [187]:
import pandas as pd
from pandas import DataFrame, Series
import numpy as np
import scipy

from  plotly.offline import plot

In [193]:
import plotly.plotly as py

In [191]:
import plotly

In [192]:
plotly.tools.set_credentials_file(username='SeanL90', api_key='sMYwRVBV0WaXn1Z8ZqJY')

In [127]:
%pwd

'C:\\Users\\Student\\Downloads'

In [128]:
from plotly.graph_objs import *

from plotly.offline import download_plotlyjs, init_notebook_mode, iplot

from sklearn import preprocessing, metrics

from sklearn.cross_validation import train_test_split, cross_val_score

from sklearn.neighbors import KNeighborsClassifier

from sklearn.ensemble import RandomForestClassifier

from sklearn.tree import DecisionTreeClassifier

from sklearn.grid_search import GridSearchCV, RandomizedSearchCV

from scipy.stats.distributions import randint

In [2]:
!pip install plotly

  Running setup.py bdist_wheel for plotly: started
  Running setup.py bdist_wheel for plotly: finished with status 'done'
  Stored in directory: C:\Users\Student\AppData\Local\pip\Cache\wheels\0c\3e\07\4848195c61f659184ca41d5a614845a018ab2d2f2a705b9998
Successfully built plotly


gevent 1.3.0 has requirement cffi>=1.11.5, but you'll have cffi 1.10.0 which is incompatible.


In [3]:
!pip install numpy

gevent 1.3.0 has requirement cffi>=1.11.5, but you'll have cffi 1.10.0 which is incompatible.


In [4]:
!pip install pandas

gevent 1.3.0 has requirement cffi>=1.11.5, but you'll have cffi 1.10.0 which is incompatible.


In [6]:
!pip install numpy

gevent 1.3.0 has requirement cffi>=1.11.5, but you'll have cffi 1.10.0 which is incompatible.


In [129]:
from sklearn.preprocessing import scale

In [130]:
X = scale(X)

In [131]:
df = pd.read_csv(r'C:\python_projects\kub_classifier\data\wine_quality.csv')

In [132]:
df.head()

fixed_acidity  volatile_acidity  citric_acid  residual_sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free_sulfur_dioxide  total_sulfur_dioxide  density    pH  sulphates quality  
0                 11.0                  34.0   0.9978  3.51       0.56     low  
1                 25.0                  67.0   0.9968  3.20       0.68     low  
2                 15.0                  54.0   0.9970  3.26       0.65     low  
3                 17.0                  60.0   0.9980  3.16       0.58     low  
4                 11.0                  34.0   0.9978  3.51       0.56     low

In [133]:
df.quality.value_counts()

low     987
high    500
Name: quality, dtype: int64

In [134]:
header = df.columns.values

In [135]:
df.dtypes

fixed_acidity           float64
volatile_acidity        float64
citric_acid             float64
residual_sugar          float64
chlorides               float64
free_sulfur_dioxide     float64
total_sulfur_dioxide    float64
density                 float64
pH                      float64
sulphates               float64
quality                  object
dtype: object

In [136]:
wine= df.as_matrix()

C:\Users\Student\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning:

Method .as_matrix will be removed in a future version. Use .values instead.



In [137]:
type(wine)

numpy.ndarray

In [138]:
wine

array([[7.4, 0.7, 0.0, ..., 3.51, 0.56, 'low'],
       [7.8, 0.88, 0.0, ..., 3.2, 0.68, 'low'],
       [7.8, 0.76, 0.04, ..., 3.26, 0.65, 'low'],
       ...,
       [7.9, 0.41, 0.37, ..., 3.17, 0.54, 'high'],
       [7.9, 0.44, 0.37, ..., 3.16, 0.54, 'high'],
       [7.1, 0.44, 0.37, ..., 3.07, 0.43, 'high']], dtype=object)

In [139]:
wine[0,0]

7.4

In [140]:
wine[:3, 0]

array([7.4, 7.8, 7.8], dtype=object)

In [141]:
wine[:3]

array([[7.4, 0.7, 0.0, 1.9, 0.076, 11.0, 34.0, 0.9978, 3.51, 0.56, 'low'],
       [7.8, 0.88, 0.0, 2.6, 0.098, 25.0, 67.0, 0.9968, 3.2, 0.68, 'low'],
       [7.8, 0.76, 0.04, 2.3, 0.092, 15.0, 54.0, 0.997, 3.26, 0.65,
        'low']], dtype=object)

In [21]:
X = # all rows, all feature columns(not the last column
y = # all rows, just the last clumn though (quality)

SyntaxError: invalid syntax (<ipython-input-21-9f3958aacb9a>, line 1)

In [142]:
y = wine[:,-1]
X = wine[:,:-1]

In [143]:
from sklearn import preprocessing, metrics

In [144]:
le = preprocessing.LabelEncoder()

In [145]:
y = le.fit_transform(y)

In [146]:
import scipy

In [147]:
yfreq = scipy.stats.itemfreq(y)

C:\Users\Student\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning:

`itemfreq` is deprecated!
`itemfreq` is deprecated and will be removed in a future version. Use instead `np.unique(..., return_counts=True)`



In [148]:
df.describe()

fixed_acidity  volatile_acidity  citric_acid  residual_sugar  \
count    1487.000000       1487.000000  1487.000000     1487.000000   
mean        8.272966          0.465716     0.303423        2.898588   
std         1.784884          0.192836     0.180989        2.198372   
min         4.600000          0.080000     0.000000        0.900000   
25%         7.000000          0.317500     0.170000        1.900000   
50%         7.900000          0.440000     0.320000        2.200000   
75%         9.200000          0.600000     0.430000        2.800000   
max        15.900000          1.330000     1.000000       15.500000   

         chlorides  free_sulfur_dioxide  total_sulfur_dioxide      density  \
count  1487.000000          1487.000000           1487.000000  1487.000000   
mean      0.079183            18.746469             61.755884     0.996225   
std       0.047974            12.936183             45.799977     0.002646   
min       0.012000             1.000000              6.000000     0.989000   
25%       0.059000             9.000000             25.000000     0.994965   
50%       0.076000            15.000000             47.000000     0.996720   
75%       0.088000            27.000000             93.000000     0.997905   
max       0.611000            82.000000            289.000000     1.003200   

                pH    sulphates  
count  1487.000000  1487.000000  
mean      3.293692     0.639388  
std       0.154856     0.180488  
min       2.740000     0.250000  
25%       3.190000     0.530000  
50%       3.300000     0.610000  
75%       3.390000     0.720000  
max       3.900000     2.000000

In [149]:
nrow, ncol = X.shape
data = [
    Box(
    y = X[:,i],
    name = header[i],
    marker = {'color': 'purple'},
    )for i in range(ncol)
]

layout = Layout(
    xaxis = dict(title = 'Feature'),
    yaxis = dict(title = 'Values'),
    showlegend = False
)
fig = dict(data = data, layout = layout)
iplot (fig)

In [150]:
from sklearn.neighbors import KNeighborsClassifier

In [151]:
neigh = KNeighborsClassifier()

In [152]:
from sklearn.cross_validation import train_test_split

In [163]:
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, random_state=42)

In [164]:
scipy.stats.itemfreq(ytrain)

C:\Users\Student\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning:

`itemfreq` is deprecated!
`itemfreq` is deprecated and will be removed in a future version. Use instead `np.unique(..., return_counts=True)`



array([[  0, 375],
       [  1, 740]], dtype=int64)

In [165]:
Xtrain.shape

(1115, 10)

In [166]:
Xtest.shape

(372, 10)

In [167]:
neigh.fit(Xtrain, ytrain)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [168]:
ypred = neigh.predict(Xtest)

In [169]:
ypred

array([0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,

In [170]:
accuracy = metrics.accuracy_score(ytest, ypred)

In [171]:
accuracy

0.7553763440860215

In [172]:
cm=metrics.confusion_matrix(ytest, ypred)

In [173]:
cm

array([[ 71,  54],
       [ 37, 210]], dtype=int64)

In [174]:
F1=metrics.f1_score(ytest, ypred)

In [175]:
F1

0.821917808219178

In [176]:
from sklearn.linear_model import SGDClassifier

In [177]:
clf = SGDClassifier()



In [178]:
neigh.predict([[1,34,34,56,74,32,19,46,12,6654]])

array([1], dtype=int64)

In [179]:
clf.fit(X,y)

C:\Users\Student\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:128: FutureWarning:

max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.



SGDClassifier(alpha=0.0001, average=False, class_weight=None, epsilon=0.1,
       eta0=0.0, fit_intercept=True, l1_ratio=0.15,
       learning_rate='optimal', loss='hinge', max_iter=None, n_iter=None,
       n_jobs=1, penalty='l2', power_t=0.5, random_state=None,
       shuffle=True, tol=None, verbose=0, warm_start=False)

In [180]:
yPred = clf.predict(Xtest)

In [194]:
f1 = 0

f2 = 1

f3 = 2

 

desc = dict(

    classes = [1, 0],

    colors  = ["orange", "blue"],

    labels  = ['Low Quality ("1")', 'High Quality ("0")'],

    symbols = ["x", "circle"]

)

 

data = [

    Scatter3d(

        x = X[y == desc["classes"][i], f1],

        y = X[y == desc["classes"][i], f2],

        z = X[y == desc["classes"][i], f3],

        name = desc["labels"][i],

        mode = "markers",

        marker = dict(

            size = 2.5,

            symbol = desc["symbols"][i],

            color  = desc["colors"][i]

        )

    ) for i in range(len(desc["labels"]))

]

 

layout = Layout(

    scene=Scene(

        xaxis=XAxis(title=header[f1], titlefont=dict(size=11)),

        yaxis=YAxis(title=header[f2], titlefont=dict(size=11)),

        zaxis=ZAxis(title=header[f3], titlefont=dict(size=11))

    ),

    margin=Margin(l=80, r=80, b=0, t=0, pad=0, autoexpand=True),

    height= 600,

)

 

fig = dict(data = data, layout = layout)

 

py.iplot(fig)

High five! You successfully sent some data to your account on plotly. View your plot in your browser at https://plot.ly/~SeanL90/0 or inside your plot.ly account where it is named 'plot from API'


In [196]:
# now lets have a scatter plot for each combination!

from plotly import tools

 

# so as not to be too crowded we are creating a grid of subplots 5 x 5

fig = tools.make_subplots(rows = 11, cols = 11, shared_xaxes = True, shared_yaxes = True)

 

for row in range(0, 10):  # here we define the 4 row50):  # and the 4 cols

        # low quality scatter (class 1) represented with an orange marker

        trace1 = Scatter(

            # based on our analysis and histogram we might assign 7

            # as the cutoff between good and bad Wined (remember Y is our label)

            x = X[y < 8, col],  # Y refers to the Y Label created right at the beginning (X are the features)

            y = X[y < 8, row],

            mode = 'markers',

            name = 'Poor Quality ("1")',

            marker = dict(

                color = 'orange',

                symbol = 'x',

                opacity = .5

            )

        )

        # High quality scatter (class 1) represented with an orange marker

        trace2 = Scatter(

            # based on our analysis and histogram we might assign 7

            # as the cutoff between good and bad Wined (remember Y is our label)

            x = X[y >= 8, col],  # Y refers to the Y Label created right at the beginning (X are the features)

            y = X[y >= 8, row],

            mode = 'markers',

            name = 'High Quality ("0")',

            marker = dict(

                color = 'blue',

                symbol = 'circle',

                opacity = .5

            )

        )

        posX = row+1

        posY = col+1

        fig.append_trace(trace1, posX, posY)

        fig.append_trace(trace2, posX, posY)

        fig['layout']['xaxis'+str(posX)].update(title=header[row])

        fig['layout']['yaxis'+str(posY)].update(title=header[col])

       

fig['layout'].update(

    showlegend = False,

    height = 900

)

py.iplot(fig)

This is the format of your plot grid:
[ (1,1) x1,y1 ]      [ (1,2) x2,y1 ]      [ (1,3) x3,y1 ]      [ (1,4) x4,y1 ]      [ (1,5) x5,y1 ]      [ (1,6) x6,y1 ]      [ (1,7) x7,y1 ]      [ (1,8) x8,y1 ]      [ (1,9) x9,y1 ]      [ (1,10) x10,y1 ]    [ (1,11) x11,y1 ]  
[ (2,1) x1,y2 ]      [ (2,2) x2,y2 ]      [ (2,3) x3,y2 ]      [ (2,4) x4,y2 ]      [ (2,5) x5,y2 ]      [ (2,6) x6,y2 ]      [ (2,7) x7,y2 ]      [ (2,8) x8,y2 ]      [ (2,9) x9,y2 ]      [ (2,10) x10,y2 ]    [ (2,11) x11,y2 ]  
[ (3,1) x1,y3 ]      [ (3,2) x2,y3 ]      [ (3,3) x3,y3 ]      [ (3,4) x4,y3 ]      [ (3,5) x5,y3 ]      [ (3,6) x6,y3 ]      [ (3,7) x7,y3 ]      [ (3,8) x8,y3 ]      [ (3,9) x9,y3 ]      [ (3,10) x10,y3 ]    [ (3,11) x11,y3 ]  
[ (4,1) x1,y4 ]      [ (4,2) x2,y4 ]      [ (4,3) x3,y4 ]      [ (4,4) x4,y4 ]      [ (4,5) x5,y4 ]      [ (4,6) x6,y4 ]      [ (4,7) x7,y4 ]      [ (4,8) x8,y4 ]      [ (4,9) x9,y4 ]      [ (4,10) x10,y4 ]    [ (4,11) x11,y4 ]  
[ (5,1) x1,y5 ]      [ (5,2) x2,y5 ]      

C:\Users\Student\Anaconda3\lib\site-packages\plotly\api\v1\clientresp.py:40: UserWarning:

Estimated Draw Time Too Long

